type Func<A, B> =
  | ((d: A) => Promise<B>)
  | ((d: A) => B);

export function pipe<A>(): (d: A) => A;
export function pipe<A, B>(
  f1: Func<A, B>,
): (d: A) => B;
export function pipe<A, B, C>(
  f1: Func<A, B>,
  f2: Func<B, C>,
): (d: A) => C;
export function pipe<A, B, C, D>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
): (d: A) => D;
export function pipe<A, B, C, D, E>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
): (d: A) => E;
export function pipe<A, B, C, D, E, F>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
): (d: A) => F;
export function pipe<A, B, C, D, E, F, G>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
): (d: A) => G;
export function pipe<A, B, C, D, E, F, G, H>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
): (d: A) => H;
export function pipe<A, B, C, D, E, F, G, H, I>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
): (d: A) => I;
export function pipe<A, B, C, D, E, F, G, H, I, J>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
): (d: A) => J;
export function pipe<A, B, C, D, E, F, G, H, I, J, K>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
): (d: A) => K;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
): (d: A) => L;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
): (d: A) => M;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
): (d: A) => N;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
): (d: A) => O;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
): (d: A) => P;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
): (d: A) => Q;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
): (d: A) => R;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
  f18: Func<R, S>,
): (d: A) => S;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
  f18: Func<R, S>,
  f19: Func<S, T>,
): (d: A) => T;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
  f18: Func<R, S>,
  f19: Func<S, T>,
  f20: Func<T, U>,
): (d: A) => U;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
  f18: Func<R, S>,
  f19: Func<S, T>,
  f20: Func<T, U>,
  f21: Func<U, V>,
): (d: A) => V;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
  f18: Func<R, S>,
  f19: Func<S, T>,
  f20: Func<T, U>,
  f21: Func<U, V>,
  f22: Func<V, W>,
): (d: A) => W;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
  f18: Func<R, S>,
  f19: Func<S, T>,
  f20: Func<T, U>,
  f21: Func<U, V>,
  f22: Func<V, W>,
  f23: Func<W, X>,
): (d: A) => X;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
  f18: Func<R, S>,
  f19: Func<S, T>,
  f20: Func<T, U>,
  f21: Func<U, V>,
  f22: Func<V, W>,
  f23: Func<W, X>,
  f24: Func<X, Y>,
): (d: A) => Y;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
>(
  f1: Func<A, B>,
  f2: Func<B, C>,
  f3: Func<C, D>,
  f4: Func<D, E>,
  f5: Func<E, F>,
  f6: Func<F, G>,
  f7: Func<G, H>,
  f8: Func<H, I>,
  f9: Func<I, J>,
  f10: Func<J, K>,
  f11: Func<K, L>,
  f12: Func<L, M>,
  f13: Func<M, N>,
  f14: Func<N, O>,
  f15: Func<O, P>,
  f16: Func<P, Q>,
  f17: Func<Q, R>,
  f18: Func<R, S>,
  f19: Func<S, T>,
  f20: Func<T, U>,
  f21: Func<U, V>,
  f22: Func<V, W>,
  f23: Func<W, X>,
  f24: Func<X, Y>,
  f25: Func<Y, Z>,
): (d: A) => Z;
